### ISSUE TITLE
demo paper checklist

### ISSUE THREAD

**Issue by altosaar** [rohanbansal12/longform-classification#7]
- [ ] screenshot of demo or pipeline explaining the architecture. not sure what to call this (look up how code complete does it?)
- [ ] single commit of cleaned up code (ideally black/flake8) to http://github.com/the-browser - maybe under the demo paper title name for a repo, so the-browser.github.io/ranking-feature-writing
- [ ] intro paragraph with framing
- [ ] method section: description of rankfromsets model
- [ ] data: description of dataset from thebrowser and longform/longreads
- [ ] quantitative evaluation: report test set recall on adversarial articles (and describe how these were generated, by scraping top sources on browser/longform/longreads)
- [ ] qualitative/quantitative human evaluation: ask robert to check boxes out of the top 50 or top 100 (ideally top 100?), over the past 30 days of RSS feeds in his OPML

**Comment by altosaar** [comment]
related work:
- https://pa.media/radar/#
- https://www.newsworthy.se/en/
- http://www.nickdiakopoulos.com/wp-content/uploads/2020/03/Comp-News-Discovery.pdf
